import { Construct } from 'constructs';
import { SecretValue } from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';

export class EinkgenSecrets extends Construct {
  public readonly openaiApiKey: secretsmanager.Secret;
  public readonly deviceStatusToken: secretsmanager.Secret;
  public readonly adminPassword: secretsmanager.Secret;
  public readonly adminCookieSigningKey: secretsmanager.Secret;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    // Plaintext placeholder. Operator overwrites via:
    //   aws secretsmanager put-secret-value --secret-id einkgen/openai_api_key \
    //     --secret-string "sk-..."
    // We use unsafePlainText for the placeholder so CloudFormation creates the
    // secret deterministically; the value is rotated by operator post-deploy.
    this.openaiApiKey = new secretsmanager.Secret(this, 'OpenAiApiKey', {
      secretName: 'einkgen/openai_api_key',
      description: 'OpenAI API key for the generator Lambda. Rotate by put-secret-value.',
      secretStringValue: SecretValue.unsafePlainText('REPLACE_ME_POST_DEPLOY'),
    });

    this.deviceStatusToken = new secretsmanager.Secret(this, 'DeviceStatusToken', {
      secretName: 'einkgen/device_status_token',
      description: 'Shared secret validated by the device-status Lambda X-Device-Token header.',
      secretStringValue: SecretValue.unsafePlainText('REPLACE_ME_POST_DEPLOY'),
    });

    // Admin password for the SPA's Admin tab login. Same lifecycle pattern as
    // the OpenAI key — placeholder on first deploy, operator runs
    //   aws secretsmanager put-secret-value --secret-id einkgen/admin_password \
    //     --secret-string '<chosen password>'
    // post-deploy. Comparison is constant-time (hmac.compare_digest); rotation
    // takes effect within TOKEN_CACHE_TTL_SECONDS (5 min) on warm Lambdas.
    this.adminPassword = new secretsmanager.Secret(this, 'AdminPassword', {
      secretName: 'einkgen/admin_password',
      description:
        'Password the operator types into the SPA Admin tab. Rotate by put-secret-value.',
      secretStringValue: SecretValue.unsafePlainText('REPLACE_ME_POST_DEPLOY'),
    });

    // HMAC key for signing admin session cookies. Auto-generated by CDK so
    // the operator never has to think about it. Rotating this key invalidates
    // every outstanding admin cookie — useful if a laptop is lost. Rotate by:
    //   aws secretsmanager put-secret-value --secret-id einkgen/admin_cookie_signing_key \
    //     --secret-string "$(openssl rand -base64 48)"
    this.adminCookieSigningKey = new secretsmanager.Secret(
      this,
      'AdminCookieSigningKey',
      {
        secretName: 'einkgen/admin_cookie_signing_key',
        description:
          'HMAC key signing admin session cookies. Rotate to invalidate sessions.',
        generateSecretString: {
          passwordLength: 64,
          excludePunctuation: true,
        },
      },
    );
  }
}
